In [1]:
!python -m pip install numpy

In [2]:
import numpy as np


In [3]:
num_list = [1,2,3,4]
int_arr2 = np.array(num_list)
print(type(num_list), type(int_arr2))
print(num_list)
print(int_arr2)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]


In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.array([1, '2', 3])

array(['1', '2', '3'], dtype='<U21')

In [11]:
np.array([1, 2., 3])

array([1., 2., 3.])

In [ ]:
# 2차원 배열 matrix
arr = np.array(
    [
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
    ]
    )
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# 3차원 배열 생성 - 3차원배열 Tensor
arr2 = np.array(
    [
        [[1, 2, 3, 4], 
         [5, 6, 7, 8], 
         [9, 10, 11, 12]],

        [[13, 14, 15, 16], 
         [17, 18, 19, 20], 
         [21, 22, 23, 24]]
    ]
)
print(arr2)
print(arr2.ndim, arr2.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3 (2, 3, 4)


In [ ]:
# 배열의 차원과 크기 알아보기 
arr = np.array([1,2,3,4])
print(arr)
print(arr.ndim)

arr2 = np.array([1,2,3,4])
print(arr2)
print(arr2.shape)   # 1차원 요소수가 4개

[1 2 3 4]
1
[1 2 3 4]
(4,)


In [30]:
arr4 = np.arange(1, 11)
print(arr4)


[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
arr5 = arr4.reshape(2, 5)
print(arr5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [33]:
# 넘파이 연산 
a = np.array([1, 2, 3])

print(a + 1)
print(a - 1)
print(a + 3)
print(a / 2)

[2 3 4]
[0 1 2]
[4 5 6]
[0.5 1.  1.5]


In [ ]:
# 배열의 범위와 개수를 지정하여 생성 
arr = np.linspace(1, 10, 10)          # np.linspace(시작인덱스 : 끝인덱스 : 개수n) - 시작 인덱스부터 끝까지 n개의 요소를 갖는 넘파이 배열 생성
print(arr)
print(arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [36]:
arr7 = np.linspace(1, np.pi, 10)          # np.linspace(시작인덱스 : 끝인덱스 : 개수n) - 시작 인덱스부터 끝까지 n개의 요소를 갖는 넘파이 배열 생성
print(arr7)
print(arr7.dtype)

[1.         1.23795474 1.47590948 1.71386422 1.95181896 2.1897737
 2.42772844 2.66568318 2.90363791 3.14159265]
float64


In [41]:
# 특별한 값을 갖는 배열 생성 
arr8 = np.zeros(10)
print(arr8)

arr9 = np.zeros(10, dtype=int)
print(arr9)

arr10 = np.zeros((2, 5))
print(arr10)            #matrix로 호출

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# numpy 배열 연산하기 for loop
data1 = list(range(0, 10))
data2 = [x * 2 for x in data1]
print(data2)

#map함수
data3 = list(map(lambda x: x * 2, data1))
print(data3)

# np.array 
x = np.array(data1)
x * 2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
# 도전하기 
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b) 
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [52]:
# 2차원 배열 만들고 행과 열의 개수 구하기 
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim, c.shape)

2 (2, 3)


In [ ]:
d = np.array([
    [[1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11 ,12]],
    [[11, 12, 13, 14], 
     [15, 16, 17, 18], 
     [19, 20, 21, 22]]
    ])

print(d.ndim) 
print(d.shape)
print(d.size)  #어레이 안에 있는 전체 엘리먼트의 개수

3
(2, 3, 4)
24


In [59]:
# numpy 배열의 인덱싱 
a = np.array([0, 1, 2, 3, 4])

print(a[2])
print(a[-1])

2
4


In [72]:
# 다음 배열에서 0,1,5 값 뽑아내기 
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0][0])
print(a[0][1])
print(a[1][2])

0
1
5


In [84]:
# numpy 배열 슬라이싱 

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[0]) 
print(a[0][1], a[1][1])
print(a[:,1])
print(a[1,1 :])
print(a[:2, :2])

[0 1 2 3]
1 5
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [85]:
# numpy 배열 fancy indexing (불리언 방식)

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [89]:
condition = a % 2 == 0
print(a[condition])
print(a[a % 2 == 0])

[0 2 4 6 8]
[0 2 4 6 8]


In [99]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# 0,0 1,0 2,0 ,   0,3 1,3 2,3
a[ (a % 4 == 1) | (a % 4 == 0)]

array([ 1,  4,  5,  8,  9, 12])

In [101]:
a[[2, 0, 1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [109]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#3의 배수 찾기
print(x[x % 3 == 0])

#4로 나누면 1이 남는 수 찾기 
print(x[x % 4 == 1])

#3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
print(x[(x % 3 == 0) & (x % 4 == 1)] )

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
